spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kjyq?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: TeAmoMessi10cs!_
  redis:
    database: 0
    host: 127.0.0.1
    password: TeAmoMessi10tm
    port: 6379