spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fight?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 993344
  redis:
    database: 3
    host: 127.0.0.1
    password:
    port: 6379